/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import CoffeCupModel from '../assets/3d/gujurly.glb'

const CoffeCup = (props) => {
  const CoffeCupRef = useRef();

  const { nodes, materials } = useGLTF(CoffeCupModel)
  
  return (
    <a.group {...props}>
      <a.group ref={CoffeCupRef} position={[0.058, 0.979, 0.026]}>
        <mesh

          geometry={nodes.Cylinder.geometry}
          material={materials.white}
        />
        <mesh

          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.002']}
        />
        <mesh

          geometry={nodes.Cylinder_2.geometry}
          material={materials['Material.003']}
        />
      </a.group>
    </a.group>
  )
}

export default CoffeCup;
